### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by z2z** [teamclouday/AndroidSteering#1]
Hi, 

Thanks 👍 

I had hard time configuring this with NFS6 Hot Pursuit. Difficult to get correct axis while configuring mapping inside the game. 

Quick ref to another similar projects projects based on vjoy. 
https://touchracer.com/ -- (smooth, POV - continuous )
https://900steeringwheel.wordpress.com/ -- Wifi (option to choose ip)

**Comment by teamclouday** [comment]
You can check your controller mappings on Windows settings -> Devices and Printers -> right click on your controller -> game controller settings -> select properties for vJoy device  
If it is fine, then probably there's some bug in the code, then I will look into it  
Also, thanks for the links

**Comment by teamclouday** [comment]
I just tried setup with steam controller. Seems that RT, LT buttons are not working.  
Now fixed it in the latest release.  
ffdfdc3667bf7cee1fe9d62b9410f1024483fb71

**Comment by z2z** [comment]
Thanks, I will test it in sometime.

NFSHP2 is available at https://www.myabandonware.com/game/need-for-speed-hot-pursuit-2-dna

**Comment by teamclouday** [comment]
I set up steam controller like this:  
![image](https://user-images.githubusercontent.com/22620163/79984421-21b97b80-8477-11ea-8884-87cc689e76a7.png)  
Since I only have steam games, the program was only tested with steam controller settings. 
I will try HFSHP2, but no guarantee for compatibility.

**Comment by teamclouday** [comment]
Hi, just tried HFSHP2 on Windows 10. Works pretty well. Here's my controller setting:  
![Screenshot (3)](https://user-images.githubusercontent.com/22620163/80002884-3c4b1f00-848e-11ea-8310-4c12689e862c.png)  
You can set up steering, gas and brake by moving your phone. It should eventually look like the mapping in the picture.  
For other buttons, simply tap the button on phone to define your own setting.
