### ISSUE TITLE
Use virtual gravity sensor instead of accelerometer

### ISSUE THREAD

**Issue by Dadido3** [teamclouday/AndroidSteering#8]
Hello,

the app itself works really well, but there is one thing that makes it hardly usable for me:
You are querying the accelerometer to determine the steering angle, which means that any lateral acceleration of the phone will cause a change in the steering angle.

An easy fix for this is to use a different sensor like `Sensor.TYPE_GRAVITY`, which is a fusion of the acceleration and gyroscope sensors (And possibly more sensors) and returns an estimated gravitational acceleration vector. It's only a two line change to apply this change, see my [pull request for the BeamNG remote controll app](https://github.com/BeamNG/remotecontrol/pull/13/files), which had the same issue.

This fix should make steering feel much more "direct".

**Comment by teamclouday** [comment]
Hey, thanks for that info! I'm busy recently but will definitely try it afterwards

**Comment by teamclouday** [comment]
Hey, just an update. I've tried the gravity sensor and it worked well. I'll release this together with future release. Thanks again!

**Comment by Dadido3** [comment]
Thank you for your time and for fixing the problem.
