### ISSUE TITLE
Analog Sticks?

### ISSUE THREAD

**Issue by defkev** [teamclouday/AndroidSteering#9]
Nice little tool!

I am trying to use this with RPCS3 as a second controller, the left stick works as expect but the right is centered at the bottom left causing e.g. the camera to deadlock rotate:

![rpcs3](https://user-images.githubusercontent.com/5265345/198885411-9cd36c0f-9776-45eb-a6a4-4c9aeed1f709.png)

furthermore where are the GamePad Analog Sticks?
Oddly LT/RT seem to control the X/Y axis of the right stick in that mode:

![sticks](https://user-images.githubusercontent.com/5265345/198885674-72fbaa95-2d3c-4b34-9442-abe350d4b556.png)

Cheers

**Comment by teamclouday** [comment]
Aha this is probably caused by a misconfiguration of the axes. In my setup, I use `Z` and `Rz` for LT/RT, referring to the xbox controller. I guess RPCS3 matches it to the right analog stick. These two axes are by default zero, and that's why it locks to the bottom left corner.

![image](https://user-images.githubusercontent.com/22620163/198889120-68d88932-b609-4d34-9cab-1e275d12e250.png)

So in your config menu, you should probably try:\
__left stick__:
* left, right -> `X`
* up, down -> `Y`

__right stick__:
* left, right -> `Rx`
* up, down -> `Ry`

__LT RT__:
* LT -> `Z`
* RT -> `Rz`

Why are L2 R2 buttons in the config?

The reason I didn't add analog sticks on Android app is because I'm not sure how to implement or design it.\
You may not notice it on your phone but on my phone there's not really much space on two sides. And yes I agree that these two sticks should be added.\
Do you have any suggestions?

**Comment by defkev** [comment]
Okay so after some fiddeling around i somewhat got it working with the (Default) Steering control option:

![androidsteering](https://user-images.githubusercontent.com/5265345/198911812-67aef916-f55d-42c0-a11a-ca98aafa3031.png)

The problem seems to be the mapping reported by the different Wheel app modes:

Steering (Default):
* left stick: left/right -> X-/+ -> center is 50% on the X axis -> Okay
* right stick: up/down -> R/Z -> center is 0% on the R/Z axis respectively -> Shouldn't this be R-/+ ???

Steering (Alternative):
* left stick: left/right -> X-/+ -> center is 50% on the X axis -> Okay
* right stick: up/down -> Not working -> ???

Gamepad:
* left stick: left/right -> Not working -> ???
* right stick: RT is R and LT is Z -> ???

Considering implementing left/right stick i would probably start with https://github.com/controlwear/virtual-joystick-android and work from there, regarding the actual design maybe something like this:

![gamepadsketch](https://user-images.githubusercontent.com/5265345/198914720-06449e1e-e741-48d1-9ce6-54d713639e4a.png)

9000 hours in MSPaint 🤣

**Comment by teamclouday** [comment]
In fact the three modes on the Android app are using the same mapping.\
If you would like to press/trigger a certain input key for mapping in applications like RPCS3 or steam, you could use the controller configuration on desktop app:

![image](https://user-images.githubusercontent.com/22620163/198920276-93d2113b-cf29-45d9-9035-ee7a5c73cd29.png)

And thanks for sharing the android virtual joystick and creating a design in MSPaint! I really like the design!\
I'll try to spend some time on this app in the following weeks and implement it👍

**Comment by defkev** [comment]
Okay nvm, if i use the Map Controller Buttons window to map the right stick in RPCS3 it becomes:

up/down -> U+/- -> Ry in vJoyMonitor
left/right -> V-/+ -> Rx in vJoyMonitor

**Comment by teamclouday** [comment]
> up/down -> U+/- -> Ry in vJoyMonitor
left/right -> V-/+ -> Rx in vJoyMonitor

Yep it looks correct

**Comment by teamclouday** [comment]
Hey I've released version 2.3.0 with your design!\
Please let me know if it works well on your phone 🙂

**Comment by defkev** [comment]
This works great so far, the scaling could definitely be improved, lots of empty space on my screen 😄 

![Screenshot_20221107-022521_Trebuchet](https://user-images.githubusercontent.com/5265345/200208156-cac83d8d-73fc-458d-a33c-daf92faa474b.png)

Tho its one of the better controller emulator i have tested over the past week, easy setup and works out of the box.

Consider putting it on F-Droid so more people can see it:
https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide/

Cheers

**Comment by teamclouday** [comment]
Awesome! Yeah I need to take some time to learn how to fit different Android screen DPIs.\
Thanks for suggesting F-Droid! I'll learn to use it 🙂

**Comment by teamclouday** [comment]
Btw, I've just updated the Android layout. Hopefully the scaling is better now
